services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - mongo-network
    volumes:
      - mongodb-data:/data/db
      - ./db/init:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo-network

  fastfood-api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    env_file:
      .env
    restart: always
    ports:
      - 8080:8080
    networks:
      - mongo-network
    depends_on:
      - mongo

networks: 
    mongo-network:
      driver: bridge

volumes:
  mongodb-data: