name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -f src/Drivers/Api/Dockerfile -t ${{ secrets.ECR_REPOSITORY_FAST_FOOD_API }}:${IMAGE_TAG} .

      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker tag ${{ secrets.ECR_REPOSITORY_FAST_FOOD_API }}:$IMAGE_TAG $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_FAST_FOOD_API }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_FAST_FOOD_API }}:$IMAGE_TAG
